#!/bin/bash
kubectl delete tfjob job1-queue-salr
kubectl delete tfjob job2-queue-salr
kubectl delete tfjob job3-queue-salr
kubectl delete tfjob job4-queue-salr
kubectl delete tfjob job5-queue-salr
kubectl delete tfjob job6-queue-salr
kubectl delete tfjob job7-queue-salr
kubectl delete tfjob job8-queue-salr
kubectl delete tfjob job9-queue-salr
kubectl delete tfjob job10-queue-salr
kubectl delete tfjob job11-queue-salr
kubectl delete tfjob job12-queue-salr
kubectl delete tfjob job1-non-queue-salr
kubectl delete tfjob job2-non-queue-salr
kubectl delete tfjob job3-non-queue-salr
kubectl delete tfjob job4-non-queue-salr
kubectl delete tfjob job5-non-queue-salr
kubectl delete tfjob job6-non-queue-salr
kubectl delete tfjob job7-non-queue-salr
kubectl delete tfjob job8-non-queue-salr
kubectl delete tfjob job9-non-queue-salr
kubectl delete tfjob job10-non-queue-salr
kubectl delete tfjob job11-non-queue-salr
kubectl delete tfjob job12-non-queue-salr