#!/bin/bash
kubectl delete tfjob job1-queue-salr
kubectl delete tfjob job2-queue-salr
kubectl delete tfjob job3-queue-salr
kubectl delete tfjob job4-queue-salr
kubectl delete tfjob job5-queue-salr
kubectl delete tfjob job6-queue-salr
kubectl delete tfjob job7-queue-salr
kubectl delete tfjob job8-queue-salr
kubectl delete tfjob job9-queue-salr
kubectl delete tfjob job10-queue-salr
kubectl delete tfjob job11-queue-salr
kubectl delete tfjob job12-queue-salr
kubectl delete tfjob job1-queue-non-salr
kubectl delete tfjob job2-queue-non-salr
kubectl delete tfjob job3-queue-non-salr
kubectl delete tfjob job4-queue-non-salr
kubectl delete tfjob job5-queue-non-salr
kubectl delete tfjob job6-queue-non-salr
kubectl delete tfjob job7-queue-non-salr
kubectl delete tfjob job8-queue-non-salr
kubectl delete tfjob job9-queue-non-salr
kubectl delete tfjob job10-queue-non-salr
kubectl delete tfjob job11-queue-non-salr
kubectl delete tfjob job12-queue-non-salr