apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "job3"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/dynamic-resource-scheduler-1/tf-dist-mnist-test:1.0
    Worker:
      replicas: 4
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/dynamic-resource-scheduler-1/tf-dist-mnist-test:1.0
