apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: job3
spec:
  max-instances: 1
  min-instances: 1
  priority: 1
  cleanPodPolicy: "Running"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://raw.githubusercontent.com/arspy77/erudite/testing_salr/examples/resnet18.py | python3 -'
            command:
            - /bin/bash
            - -c
            image: gcr.io/large-batch-training/keras-container
            name: keras-container
            ports:
            - containerPort: 2222
              name: tfjob-port
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://raw.githubusercontent.com/arspy77/erudite/testing_salr/examples/resnet18.py | python3 -'
            env:
            - name: global_steps
              value: "100000"
            - name: use_salr
              value: "True"
            command:
            - /bin/bash
            - -c
            image: gcr.io/large-batch-training/keras-container
            name: keras-container
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "4"
                memory: "16Gi"
