apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: job4
spec:
  max-instances: 6
  min-instances: 2
  priority: 100
  cleanPodPolicy: "All"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://raw.githubusercontent.com/arspy77/erudite/testing_salr/examples/mnist-df-3.py | python3 -'
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.15.0-py3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://raw.githubusercontent.com/arspy77/erudite/testing_salr/examples/mnist-df-3.py | python3 -'
            env:
            - name: epoch
              value: "20"
            - name: use_salr
              value: "True"
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.15.0-py3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "3"
                memory: "6Gi"
